BACKLIGHT_ENABLE = yes
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE   = yes
CONSOLE_ENABLE   = yes
EXTRAKEY_ENABLE  = yes
MOUSEKEY_ENABLE  = yes
RGBLIGHT_ENABLE  = no
TAP_DANCE_ENABLE = no

LAYOUTS = LAYOUT_65_split_space_bs_rshift
